#!/usr/bin/env python

"""
Generate manifest YAML files from a CSV file.

CSV file should contain list of properties and some metadata.

Usage:

    $ env/bin/python scripts/csv-to-manifest path/to.csv

"""

import pathlib

import click

from lodam.services.gsheets import get_csv_rows
from lodam.services.gsheets import load_spinta_context
from lodam.services.gsheets import update_manifest_files


@click.command()
@click.argument('csv')
def main(csv: str):
    rows = get_csv_rows(pathlib.Path(csv))
    context = load_spinta_context()
    update_manifest_files(context, rows)


if __name__ == "__main__":
    main()
