#!/usr/bin/env python

"""
Generate inventory CSV file from manifest YAML files.

Usage:

    $ env/bin/python scripts/manifest-to-csv path/to/manifest

"""

import pathlib
import sys

import click

from lodam.services.inventory import manifest_to_inventory, writecsv


@click.command()
@click.argument('manifest')
@click.option('-o', '--output', help="output file")
def main(manifest: str, output: str):
    table = manifest_to_inventory(pathlib.Path(manifest))
    if output:
        with open(output, 'w') as f:
            writecsv(f, table)
    else:
        writecsv(sys.stdout, table)


if __name__ == "__main__":
    main()
