# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install spinta --upgrade
        spinta --version
    - name: Check manifest files
      run: |
        find datasets -iname "*.csv" | xargs spinta check --check-names
    - name: Check get_data_gov_lt.in file
      run: |
        cat get_data_gov_lt.in | xargs spinta copy -o manifest.csv
        spinta check --check-names manifest.csv
        rm manifest.csv
